#define FRAME_RATE 7
#define SEGMENT_RADIUS 9
#define APPLE_RADIUS 5
#define SEGMENT_SPACING 30
#define GRID_HEIGHT 10
#define GRID_WIDTH 15
#define HEIGHT (SEGMENT_SPACING * GRID_HEIGHT)
#define WIDTH (SEGMENT_SPACING * GRID_WIDTH)