#define FRAME_RATE 8
#define SEGMENT_RADIUS 9
#define APPLE_RADIUS 5
#define SEGMENT_SPACING 20
#define GRID_HEIGHT 21
#define GRID_WIDTH 35
#define HEIGHT (SEGMENT_SPACING * GRID_HEIGHT)
#define WIDTH (SEGMENT_SPACING * GRID_WIDTH)